version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - save_cache: 
          key: "npm package"
          paths: 
            - "/src/node_modules"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - restore_cache:
            key: "npm package"
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - restore_cache:
            key: "npm package"
      - run: npm i
      - run: npm audit
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
              - build
      - analyze:
          requires:
              - build
              - test
