version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "build"
          command: "npm i"
      - run: 
          command: "npm run lint"
      - save_cache: 
          key: "npm package"
          path: "/rc/node_modules"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          restore_cache:
            key: "npm package"
      - run: "npm i"
      - run: "npm run test"
  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          restore_cache:
            key: "npm package"
      - run: "npm i"
      - run:
          command: "npm audit"
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test
          requires:
            - build
      - analyze
          requires:
            - test
