version: 2.1
jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "build"
          command: "npm i"
      - run: 
          command: "npm run lint"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: "npm run test"
  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: "npm audit"
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test
        required:
          - build
      - analyze
        required:
          - test
